name: 小说更新
on:
#  schedule:
#    - cron:  '*/15 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 执行JS
        run: |
          yarn
          node ./node-crawler/novel-update.js ${{ secrets.accessKeyId }} ${{ secrets.secretAccessKey }}

